/*
 * MIT License
 *
 * Copyright (c) 2023 Jeremy O'Brien
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#pragma once

#ifdef SIGNAL_TUNE_DEFAULT
int8_t signal_tune[] = {
    BUZZER_NOTE_C8, 5,
    BUZZER_NOTE_REST, 6,
    BUZZER_NOTE_C8, 5,
    0
};
#endif // SIGNAL_TUNE_DEFAULT

#ifdef SIGNAL_TUNE_ZELDA_SECRET
int8_t signal_tune[] = {
    BUZZER_NOTE_G5, 8,
    BUZZER_NOTE_F5SHARP_G5FLAT, 8,
    BUZZER_NOTE_D5SHARP_E5FLAT, 8,
    BUZZER_NOTE_A4, 8,
    BUZZER_NOTE_G4SHARP_A4FLAT, 8,
    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_G5SHARP_A5FLAT, 8,
    BUZZER_NOTE_C6, 20,
    0
};
#endif // SIGNAL_TUNE_ZELDA_SECRET

#ifdef SIGNAL_TUNE_MARIO_THEME
int8_t signal_tune[] = {
    BUZZER_NOTE_E6, 7,
    BUZZER_NOTE_REST, 2,
    BUZZER_NOTE_E6, 7,
    BUZZER_NOTE_REST, 10,
    BUZZER_NOTE_E6, 7,
    BUZZER_NOTE_REST, 11,
    BUZZER_NOTE_C6, 7,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_E6, 7,
    BUZZER_NOTE_REST, 10,
    BUZZER_NOTE_G6, 8,
    BUZZER_NOTE_REST, 30,
    BUZZER_NOTE_G5, 8,
    0
};
#endif // SIGNAL_TUNE_MARIO_THEME

#ifdef SIGNAL_TUNE_MGS_CODEC
int8_t signal_tune[] = {
    BUZZER_NOTE_B5, 1,
    BUZZER_NOTE_E6, 1,
    BUZZER_NOTE_B5, 1,
    BUZZER_NOTE_E6, 1,
    BUZZER_NOTE_B5, 1,
    BUZZER_NOTE_E6, 1,
    BUZZER_NOTE_B5, 1,
    BUZZER_NOTE_E6, 1,
    BUZZER_NOTE_B5, 1,
    BUZZER_NOTE_E6, 1,
    BUZZER_NOTE_REST, 6,
    BUZZER_NOTE_B5, 1,
    BUZZER_NOTE_E6, 1,
    BUZZER_NOTE_B5, 1,
    BUZZER_NOTE_E6, 1,
    BUZZER_NOTE_B5, 1,
    BUZZER_NOTE_E6, 1,
    BUZZER_NOTE_B5, 1,
    BUZZER_NOTE_E6, 1,
    BUZZER_NOTE_B5, 1,
    BUZZER_NOTE_E6, 1,
    0
};
#endif // SIGNAL_TUNE_MGS_CODEC

#ifdef SIGNAL_TUNE_KIM_POSSIBLE
int8_t signal_tune[] = {
    BUZZER_NOTE_C6, 6,
    BUZZER_NOTE_E6, 6,
    BUZZER_NOTE_G6, 6,
    BUZZER_NOTE_C7, 6,
    0
};
#endif // SIGNAL_TUNE_KIM_POSSIBLE

#ifdef SIGNAL_TUNE_POWER_RANGERS
int8_t signal_tune[] = {
    BUZZER_NOTE_G5, 6,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_G5, 6,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_F5, 6,
    BUZZER_NOTE_REST, 2,
    BUZZER_NOTE_G5, 6,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_A5SHARP_B5FLAT, 6,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_G5, 6,
    0
};
#endif // SIGNAL_TUNE_POWER_RANGERS

#ifdef SIGNAL_TUNE_LAYLA
int8_t signal_tune[] = {
    BUZZER_NOTE_A6, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_C7, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_D7, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F7, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_D7, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_C7, 5,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_D7, 20,
    0
};
#endif // SIGNAL_TUNE_LAYLA

#ifdef SIGNAL_TUNE_HARRY_POTTER_SHORT
int8_t signal_tune[] = {
    BUZZER_NOTE_B5, 12,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_E6, 12,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_G6, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F6SHARP_G6FLAT, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_E6, 16,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_B6, 8,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_A6, 24,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F6SHARP_G6FLAT, 24,
    0
};
#endif // SIGNAL_TUNE_HARRY_POTTER_SHORT

#ifdef SIGNAL_TUNE_HARRY_POTTER_LONG
int8_t signal_tune[] = {
    BUZZER_NOTE_B5, 12,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_E6, 12,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_G6, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F6SHARP_G6FLAT, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_E6, 16,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_B6, 8,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_A6, 24,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F6SHARP_G6FLAT, 24,
    BUZZER_NOTE_REST, 1,

    BUZZER_NOTE_E6, 12,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_G6, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F6SHARP_G6FLAT, 6,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_D6SHARP_E6FLAT, 16,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_F6, 8,
    BUZZER_NOTE_REST, 1,
    BUZZER_NOTE_B5, 24,

    0
};
#endif // SIGNAL_TUNE_HARRY_POTTER_LONG

#ifdef SIGNAL_TUNE_JURASSIC_PARK
int8_t signal_tune[] = {
    BUZZER_NOTE_B5, 7,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_A5SHARP_B5FLAT, 7,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_B5, 13,
    BUZZER_NOTE_REST, 13,
    BUZZER_NOTE_F5SHARP_G5FLAT, 13,
    BUZZER_NOTE_REST, 13,
    BUZZER_NOTE_E5, 13,
    BUZZER_NOTE_REST, 13,
    BUZZER_NOTE_B5, 7,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_A5SHARP_B5FLAT, 7,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_B5, 13,
    BUZZER_NOTE_REST, 13,
    BUZZER_NOTE_F5SHARP_G5FLAT, 13,
    BUZZER_NOTE_REST, 13,
    BUZZER_NOTE_E5, 13,
    0,
};
#endif // SIGNAL_TUNE_JURASSIC_PARK

#ifdef SIGNAL_TUNE_EVANGELION
int8_t signal_tune[] = {
    BUZZER_NOTE_C5, 13,
    BUZZER_NOTE_REST, 13,
    BUZZER_NOTE_D5SHARP_E5FLAT, 13,
    BUZZER_NOTE_REST, 13,
    BUZZER_NOTE_F5, 13,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_D5SHARP_E5FLAT, 13,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_F5, 7,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_F5, 7,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_F5, 7,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_A5SHARP_B5FLAT, 7,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_G5SHARP_A5FLAT, 7,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_G5, 3,
    BUZZER_NOTE_REST, 3,
    BUZZER_NOTE_F5, 7,
    BUZZER_NOTE_REST, 7,
    BUZZER_NOTE_G5, 13,
    0,
};
#endif // SIGNAL_TUNE_EVANGELION

#ifdef SIGNAL_TUNE_NOKIA
int8_t signal_tune[] = {
    BUZZER_NOTE_E6, 8,
    BUZZER_NOTE_D6, 8,
    BUZZER_NOTE_F5SHARP_G5FLAT, 16,
    BUZZER_NOTE_G5SHARP_A5FLAT, 16,
    BUZZER_NOTE_REST, 4,
    BUZZER_NOTE_C6SHARP_D6FLAT, 8,
    BUZZER_NOTE_B5, 8,
    BUZZER_NOTE_D5, 16,
    BUZZER_NOTE_E5, 16,
    BUZZER_NOTE_REST, 4,
    0
};
#endif // SIGNAL_TUNE_NOKIA

#ifdef SIGNAL_TUNE_TETRIS
int8_t signal_tune[] = {
    BUZZER_NOTE_E5, 12,
    BUZZER_NOTE_B4, 6,
    BUZZER_NOTE_C5, 6,
    BUZZER_NOTE_D5, 12,
    BUZZER_NOTE_C5, 6,
    BUZZER_NOTE_B4, 6,
    BUZZER_NOTE_A4, 12,
    BUZZER_NOTE_REST, 2,
    BUZZER_NOTE_A4, 6,
    BUZZER_NOTE_C5, 6,
    BUZZER_NOTE_E5, 12,
    BUZZER_NOTE_D5, 6,
    BUZZER_NOTE_C5, 6,
    BUZZER_NOTE_B4, 12,
    BUZZER_NOTE_REST, 2,
    BUZZER_NOTE_C5, 6,
    BUZZER_NOTE_D5, 12,
    BUZZER_NOTE_E5, 12,
    BUZZER_NOTE_C5, 12,
    BUZZER_NOTE_A4, 12,
    BUZZER_NOTE_A4, 16,
    0
};
#endif // SIGNAL_TUNE_TETRIS

#ifdef SIGNAL_TUNE_IMPERIAL
int8_t signal_tune[] = {
    BUZZER_NOTE_G5, 12,
    BUZZER_NOTE_G5, 12,
    BUZZER_NOTE_G5, 12,
    BUZZER_NOTE_REST, 2,
    BUZZER_NOTE_D5SHARP_E5FLAT, 10,
    BUZZER_NOTE_A5SHARP_B5FLAT, 4,
    BUZZER_NOTE_G5, 12,
    BUZZER_NOTE_REST, 2,
    BUZZER_NOTE_D5SHARP_E5FLAT, 10,
    BUZZER_NOTE_A5SHARP_B5FLAT, 4,
    BUZZER_NOTE_G5, 20,
    0
};
#endif // SIGNAL_TUNE_IMPERIAL

#ifdef SIGNAL_TUNE_POKEMON
int8_t signal_tune[] = {
    BUZZER_NOTE_C6, 6,
    BUZZER_NOTE_E6, 6,
    BUZZER_NOTE_G6, 6,
    BUZZER_NOTE_C7, 6,
    BUZZER_NOTE_E7, 6,
    BUZZER_NOTE_REST, 4,
    BUZZER_NOTE_G6, 6,
    BUZZER_NOTE_E6, 6,
    BUZZER_NOTE_C6, 10,
    0
};
#endif // SIGNAL_TUNE_POKEMON

#ifdef SIGNAL_TUNE_VICTORY
int8_t signal_tune[] = {
    BUZZER_NOTE_C6, 6,
    BUZZER_NOTE_C6, 6,
    BUZZER_NOTE_C6, 6,
    BUZZER_NOTE_C6, 12,
    BUZZER_NOTE_REST, 4,
    BUZZER_NOTE_G5SHARP_A5FLAT, 6,
    BUZZER_NOTE_A5SHARP_B5FLAT, 6,
    BUZZER_NOTE_C6, 20,
    0
};
#endif // SIGNAL_TUNE_VICTORY

#ifdef SIGNAL_TUNE_TRITONE
int8_t signal_tune[] = {
    BUZZER_NOTE_A5, 8,
    BUZZER_NOTE_E6, 8,
    BUZZER_NOTE_A6, 16,
    0
};
#endif // SIGNAL_TUNE_TRITONE

#ifdef SIGNAL_TUNE_SOSUMI
int8_t signal_tune[] = {
    BUZZER_NOTE_C6, 4,
    BUZZER_NOTE_G5, 4,
    BUZZER_NOTE_E5, 4,
    BUZZER_NOTE_C5, 8,
    0
};
#endif // SIGNAL_TUNE_SOSUMI

#ifdef SIGNAL_TUNE_OLDPHONE
int8_t signal_tune[] = {
    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_G5, 8,
    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_G5, 8,
    BUZZER_NOTE_REST, 8,
    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_G5, 8,
    BUZZER_NOTE_E5, 8,
    BUZZER_NOTE_G5, 8,
    0
};
#endif // SIGNAL_TUNE_OLDPHONE

#ifdef SIGNAL_TUNE_MGS_ALERT
int8_t signal_tune[] = {
    BUZZER_NOTE_B6, 8,
    0
};
#endif // SIGNAL_TUNE_MGS_ALERT

#ifdef SIGNAL_TUNE_SONIC
int8_t signal_tune[] = {
    BUZZER_NOTE_E6, 3,
    BUZZER_NOTE_G6, 3,
    BUZZER_NOTE_C7, 6,
    0
};
#endif // SIGNAL_TUNE_SONIC

#ifdef SIGNAL_TUNE_PACMAN
int8_t signal_tune[] = {
    BUZZER_NOTE_C6, 2,
    BUZZER_NOTE_B5, 2,
    BUZZER_NOTE_A5SHARP_B5FLAT, 2,
    BUZZER_NOTE_A5, 2,
    BUZZER_NOTE_G5SHARP_A5FLAT, 2,
    BUZZER_NOTE_G5, 2,
    BUZZER_NOTE_F5SHARP_G5FLAT, 2,
    BUZZER_NOTE_F5, 2,
    BUZZER_NOTE_E5, 2,
    BUZZER_NOTE_D5SHARP_E5FLAT, 2,
    BUZZER_NOTE_D5, 2,
    BUZZER_NOTE_C5SHARP_D5FLAT, 2,
    BUZZER_NOTE_C5, 2,
    BUZZER_NOTE_B4, 2,
    BUZZER_NOTE_A4SHARP_B4FLAT, 2,
    BUZZER_NOTE_A4, 2,
    BUZZER_NOTE_G4SHARP_A4FLAT, 2,
    BUZZER_NOTE_G4, 2,
    BUZZER_NOTE_F4SHARP_G4FLAT, 2,
    BUZZER_NOTE_F4, 2,
    BUZZER_NOTE_E4, 2,
    BUZZER_NOTE_D4SHARP_E4FLAT, 2,
    BUZZER_NOTE_D4, 2,
    BUZZER_NOTE_C4SHARP_D4FLAT, 2,
    BUZZER_NOTE_C4, 2,
    BUZZER_NOTE_B3, 2,
    BUZZER_NOTE_A3SHARP_B3FLAT, 2,
    BUZZER_NOTE_A3, 2,
    BUZZER_NOTE_G3SHARP_A3FLAT, 2,
    BUZZER_NOTE_G3, 2,
    BUZZER_NOTE_F3SHARP_G3FLAT, 2,
    BUZZER_NOTE_F3, 2,
    BUZZER_NOTE_E3, 2,
    BUZZER_NOTE_D3SHARP_E3FLAT, 2,
    BUZZER_NOTE_D3, 2,
    BUZZER_NOTE_C3SHARP_D3FLAT, 2,
    BUZZER_NOTE_C3, 4,
    0
};
#endif // SIGNAL_TUNE_PACMAN

#ifdef SIGNAL_TUNE_WINERROR
int8_t signal_tune[] = {
    BUZZER_NOTE_C4, 10,
    BUZZER_NOTE_G3, 10,
    BUZZER_NOTE_C4, 10,
    0
};
#endif // SIGNAL_TUNE_WINERROR
