#include "movement_custom_alarm_tunes.h"

#include "movement_tunes_config.h"

#include <stdlib.h>

#include "watch_tcc.h"

const int8_t* alarm_tunes[MOVEMENT_N_ALARM_TUNES];
const char* alarm_tunes_names[MOVEMENT_N_ALARM_TUNES];

static const int8_t DEFAULT_NOTE_DURATION = 4;

const int8_t default_alarm_tune[] = {
    BUZZER_NOTE_C8, 3,
    BUZZER_NOTE_REST, 4,
    BUZZER_NOTE_C8, 3,
    BUZZER_NOTE_REST, 4,
    BUZZER_NOTE_C8, 3,
    BUZZER_NOTE_REST, 4,
    BUZZER_NOTE_C8, 5,
    BUZZER_NOTE_REST, 38,
    -8, 9,
    0
};

static const char* default_alarm_tune_name = "ALaRnn";

int8_t* alarm_tune = default_alarm_tune;
static uint8_t active_alarm_tune_index = 0;

#if defined ALARM_TUNE_GIGI_DAG || defined INCLUDE_ALARM_TUNE_GIGI_DAG
static const int8_t GIGI_DAG_EIGHTH_NOTE = 12;
static const int8_t GIGI_DAG_QUARTER_NOTE = GIGI_DAG_EIGHTH_NOTE * 2;

static const char* alarm_tune_gigi_dag_name = "GG dAG";
static const int8_t alarm_tune_gigi_dag[] = {
    BUZZER_NOTE_F6SHARP_G6FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6SHARP_G6FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_D7, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C7SHARP_D7FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * GIGI_DAG_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_C7SHARP_D7FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C7SHARP_D7FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_D7, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * GIGI_DAG_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, GIGI_DAG_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6SHARP_G6FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * GIGI_DAG_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    -36, 1,
    0
};
#endif // ALARM_TUNE_GIGI_DAG || INCLUDE_ALARM_TUNE_GIGI_DAG

#if defined ALARM_TUNE_TWINKLE || defined INCLUDE_ALARM_TUNE_TWINKLE
static const int8_t TWINKLE_EIGHTH_NOTE = 12;
static const int8_t TWINKLE_QUARTER_NOTE = TWINKLE_EIGHTH_NOTE * 2;

static const char* alarm_tune_twinkle_name = "STAR";
static const int8_t alarm_tune_twinkle[] = {
    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_D6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_D6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, TWINKLE_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * TWINKLE_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    -32, 1,
    0
};
#endif // ALARM_TUNE_TWINKLE || INCLUDE_ALARM_TUNE_TWINKLE


#if defined ALARM_TUNE_BABY || defined INCLUDE_ALARM_TUNE_BABY
static const int8_t BABY_EIGHTH_NOTE = 12;
static const int8_t BABY_QUARTER_NOTE = BABY_EIGHTH_NOTE * 2;

static const char* alarm_tune_baby_name = " baby";
static const int8_t alarm_tune_baby[] = {
    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6SHARP_B6FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6SHARP_B6FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_C7, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE + BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6SHARP_B6FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,

    0
};
#endif // ALARM_TUNE_BABY || INCLUDE_ALARM_TUNE_BABY

#if defined ALARM_TUNE_INTER || defined INCLUDE_ALARM_TUNE_INTER
static const int8_t INTER_EIGHTH_NOTE = 14;
static const int8_t INTER_QUARTER_NOTE = INTER_EIGHTH_NOTE * 2;

static const char* alarm_tune_inter_name = " IntEr";
static const int8_t alarm_tune_inter[] = {
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, INTER_QUARTER_NOTE + INTER_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, INTER_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, INTER_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, BABY_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, INTER_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, INTER_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_D6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, INTER_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * INTER_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    -16, 3,    
    0
};
#endif // ALARM_TUNE_INTER || INCLUDE_ALARM_TUNE_INTER

#if defined ALARM_TUNE_ELMO || defined INCLUDE_ALARM_TUNE_ELMO
static const int8_t ELMO_EIGHTH_NOTE = 10;
static const int8_t ELMO_QUARTER_NOTE = ELMO_EIGHTH_NOTE * 2;

static const char* alarm_tune_elmo_name = "ELnnO";
static const int8_t alarm_tune_elmo[] = {
    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    
    -8, 1,

    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_D6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_D6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,


    BUZZER_NOTE_D6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_D6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    -8, 1,

    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE,
    BUZZER_NOTE_C7, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C7, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 4 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 4 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C7, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C7, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * ELMO_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C7, DEFAULT_NOTE_DURATION,

    0,
};
#endif // ALARM_TUNE_ELMO || INCLUDE_ALARM_TUNE_ELMO

#if defined ALARM_TUNE_FARM || defined INCLUDE_ALARM_TUNE_FARM
static const int8_t FARM_SIXTEENTH_NOTE = 10;
static const int8_t FARM_EIGHTH_NOTE = 20;
static const int8_t FARM_QUARTER_NOTE = FARM_EIGHTH_NOTE * 2;

static const char* alarm_tune_farm_name = " FARnn";
static const int8_t alarm_tune_farm[] = {
    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_SIXTEENTH_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_D6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_D6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_SIXTEENTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_SIXTEENTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_G6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, FARM_EIGHTH_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, 2 * FARM_QUARTER_NOTE - FARM_SIXTEENTH_NOTE - DEFAULT_NOTE_DURATION,

    -28, 1,
    0,
};
#endif // ALARM_TUNE_FARM || INCLUDE_ALARM_TUNE_FARM

#if defined ALARM_TUNE_ONEOFTHESEDAYS || defined INCLUDE_ALARM_TUNE_ONEOFTHESEDAYS
static const int8_t ONEOFTHESEDAYS_THIRD_NOTE = 11;
static const int8_t ONEOFTHESEDAYS_QUARTER_NOTE = ONEOFTHESEDAYS_THIRD_NOTE * 3;

static const char* alarm_tune_days_name = " floyd";
static const int8_t alarm_tune_days[] = {
    BUZZER_NOTE_B3, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE * 2 - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B3, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE - DEFAULT_NOTE_DURATION,
    -4, 5,

    BUZZER_NOTE_B5, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE - DEFAULT_NOTE_DURATION,
    -2, 5,

    BUZZER_NOTE_A3, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE * 2 - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A3, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE - DEFAULT_NOTE_DURATION,
    -4, 5,

    BUZZER_NOTE_A5, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE - DEFAULT_NOTE_DURATION,
    -2, 5,

    BUZZER_NOTE_B3, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE * 2 - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B3, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE - DEFAULT_NOTE_DURATION,  
    -4, 5,

    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6SHARP_G6FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE * 2 - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_F6SHARP_G6FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_E6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE * 2 - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_F6SHARP_G6FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_D6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_C6SHARP_D6FLAT, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE * 2 - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_D6, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_THIRD_NOTE - DEFAULT_NOTE_DURATION,

    BUZZER_NOTE_B5, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_A5, DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_REST, ONEOFTHESEDAYS_QUARTER_NOTE - DEFAULT_NOTE_DURATION,
    BUZZER_NOTE_B5, DEFAULT_NOTE_DURATION,
    // BUZZER_NOTE_REST, ONEOFTHESEDAYS_QUARTER_NOTE - DEFAULT_NOTE_DURATION,

    0,
};
#endif // ALARM_TUNE_ONEOFTHESEDAYS || INCLUDE_ALARM_TUNE_ONEOFTHESEDAYS

void movement_custom_alarm_tunes_init(void) {
    // memset((void*)alarm_tunes, 0, sizeof(int8_t*) * MOVEMENT_N_ALARM_TUNES);
    // memset((void*)alarm_tunes_names, 0, sizeof(char*) * MOVEMENT_N_ALARM_TUNES);

    uint8_t alarm_tune_index = 0;

    alarm_tunes[alarm_tune_index] = default_alarm_tune;
    alarm_tunes_names[alarm_tune_index] = default_alarm_tune_name;

#if defined ALARM_TUNE_GIGI_DAG || defined INCLUDE_ALARM_TUNE_GIGI_DAG
    alarm_tune_index++;
    alarm_tunes[alarm_tune_index] = alarm_tune_gigi_dag;
    alarm_tunes_names[alarm_tune_index] = alarm_tune_gigi_dag_name;
#if defined ALARM_TUNE_GIGI_DAG
    active_alarm_tune_index = alarm_tune_index;
#endif // ALARM_TUNE_GIGI_DAG
#endif

#if defined ALARM_TUNE_TWINKLE || defined INCLUDE_ALARM_TUNE_TWINKLE
    alarm_tune_index++;
    alarm_tunes[alarm_tune_index] = alarm_tune_twinkle;
    alarm_tunes_names[alarm_tune_index] = alarm_tune_twinkle_name;
#if defined ALARM_TUNE_TWINKLE
    active_alarm_tune_index = alarm_tune_index;
#endif // ALARM_TUNE_TWINKLE
#endif

#if defined ALARM_TUNE_BABY || defined INCLUDE_ALARM_TUNE_BABY
    alarm_tune_index++;
    alarm_tunes[alarm_tune_index] = alarm_tune_baby;
    alarm_tunes_names[alarm_tune_index] = alarm_tune_baby_name;
#if defined ALARM_TUNE_BABY
    active_alarm_tune_index = alarm_tune_index;
#endif // ALARM_TUNE_BABY
#endif

#if defined ALARM_TUNE_INTER || defined INCLUDE_ALARM_TUNE_INTER
    alarm_tune_index++;
    alarm_tunes[alarm_tune_index] = alarm_tune_inter;
    alarm_tunes_names[alarm_tune_index] = alarm_tune_inter_name;
#if defined ALARM_TUNE_INTER
    active_alarm_tune_index = alarm_tune_index;
#endif // ALARM_TUNE_INTER
#endif // ALARM_TUNE_INTER || INCLUDE_ALARM_TUNE_INTER

#if defined ALARM_TUNE_ELMO || defined INCLUDE_ALARM_TUNE_ELMO
    alarm_tune_index++;
    alarm_tunes[alarm_tune_index] = alarm_tune_elmo;
    alarm_tunes_names[alarm_tune_index] = alarm_tune_elmo_name;
#if defined ALARM_TUNE_ELMO
    active_alarm_tune_index = alarm_tune_index;
#endif // ALARM_TUNE_ELMO
#endif // ALARM_TUNE_ELMO || INCLUDE_ALARM_TUNE_ELMO

#if defined ALARM_TUNE_FARM || defined INCLUDE_ALARM_TUNE_FARM
    alarm_tune_index++;
    alarm_tunes[alarm_tune_index] = alarm_tune_farm;
    alarm_tunes_names[alarm_tune_index] = alarm_tune_farm_name;
#if defined ALARM_TUNE_FARM
    active_alarm_tune_index = alarm_tune_index;
#endif // ALARM_TUNE_FARM
#endif // ALARM_TUNE_FARM || INCLUDE_ALARM_TUNE_FARM

#if defined ALARM_TUNE_ONEOFTHESEDAYS || defined INCLUDE_ALARM_TUNE_ONEOFTHESEDAYS
    alarm_tune_index++;
    alarm_tunes[alarm_tune_index] = alarm_tune_days;
    alarm_tunes_names[alarm_tune_index] = alarm_tune_days_name;
#if defined ALARM_TUNE_ONEOFTHESEDAYS
    active_alarm_tune_index = alarm_tune_index;
#endif // ALARM_TUNE_ONEOFTHESEDAYS
#endif // ALARM_TUNE_ONEOFTHESEDAYS || INCLUDE_ALARM_TUNE_ONEOFTHESEDAYS

    alarm_tune = alarm_tunes[active_alarm_tune_index];
}

uint8_t movement_custom_alarm_tunes_get_active_tune_index() {
    return active_alarm_tune_index;
}

void movement_custom_alarm_tunes_set_active_tune_index(uint8_t index) {
    active_alarm_tune_index = index;
    alarm_tune = alarm_tunes[active_alarm_tune_index];
}
