SRCS += \
  ./watch-faces/clock/clock_face.c \
  ./watch-faces/clock/beats_face.c \
  ./watch-faces/clock/world_clock_face.c \
  ./watch-faces/clock/mars_time_face.c \
  ./watch-faces/clock/ish_face.c \
  ./watch-faces/complication/alarm_face.c \
  ./watch-faces/complication/advanced_alarm_face.c \
  ./watch-faces/complication/countdown_face.c \
  ./watch-faces/complication/stopwatch_face.c \
  ./watch-faces/complication/fast_stopwatch_face.c \
  ./watch-faces/complication/sunrise_sunset_face.c \
  ./watch-faces/complication/moon_phase_face.c \
  ./watch-faces/complication/days_since_face.c \
  ./watch-faces/complication/breathing_face.c \
  ./watch-faces/complication/squash_face.c \
  ./watch-faces/complication/totp_face.c \
  ./watch-faces/complication/totp_lfs_face.c \
  ./watch-faces/complication/tally_face.c \
  ./watch-faces/complication/wordle_face.c \
  ./watch-faces/demo/all_segments_face.c \
  ./watch-faces/demo/character_set_face.c \
  ./watch-faces/demo/light_sensor_face.c \
  ./watch-faces/demo/peek_memory_face.c \
  ./watch-faces/demo/rtccount_face.c \
  ./watch-faces/sensor/accelerometer_status_face.c \
  ./watch-faces/sensor/temperature_display_face.c \
  ./watch-faces/sensor/temperature_logging_face.c \
  ./watch-faces/sensor/activity_logging_face.c \
  ./watch-faces/sensor/voltage_face.c \
  ./watch-faces/settings/set_time_face.c \
  ./watch-faces/settings/settings_face.c \
  ./watch-faces/settings/finetune_face.c \
  ./watch-faces/settings/nanosec_face.c \
  ./watch-faces/io/chirpy_demo_face.c \
  ./watch-faces/io/irda_upload_face.c \
  ./watch-faces/complication/probability_face.c \
  ./watch-faces/clock/close_enough_face.c \
  ./watch-faces/complication/tarot_face.c \
  ./watch-faces/complication/kitchen_conversions_face.c \
  ./watch-faces/complication/periodic_table_face.c \
  ./watch-faces/clock/ke_decimal_time_face.c \
  ./watch-faces/complication/baby_kicks_face.c \
  ./watch-faces/complication/counter_face.c \
  ./watch-faces/complication/pulsometer_face.c \
  ./watch-faces/complication/interval_face.c \
  ./watch-faces/complication/timer_face.c \
  ./watch-faces/complication/simple_coin_flip_face.c \
  ./watch-faces/sensor/lis2dw_monitor_face.c \
  ./watch-faces/complication/wareki_face.c \
  ./watch-faces/complication/deadline_face.c \
  ./watch-faces/complication/blackjack_face.c \
  ./watch-faces/complication/endless_runner_face.c \
  ./watch-faces/complication/higher_lower_game_face.c \
  ./watch-faces/complication/lander_face.c \
  ./watch-faces/complication/simon_face.c \
# New watch faces go above this line.
